### ISSUE TITLE
[REFACTOR] Overall roadmap of project

### ISSUE THREAD

**Issue by alowave223** [alowave223/osu-ua-tracker#1]
List of TODO's that would be tracked and updated as ideas come to my mind. Feel free to make contributions!

- [ ] Go through code and remove unnecessary/unused/repetitive code.
- [ ] Make updater asynchronous
- [ ] Add support for all gamemodes
   - [x] osu! Standart
   - [ ] osu! Mania
   - [ ] osu! Catch
   - [ ] osu! Taiko
- [ ] Switch database to Redis
- [ ] Make discord embed show exact score position in player's top 50
